delete from angels where 1 = 1;
INSERT INTO angels VALUES
('dcnWr1xsTVOGKybVHvTZ5w==', null, 'Hannu',     'Huhtanen', 'hannu@huhtanen.eu',            '0123456789',   'Helsinki',     'Finland', 'Just a guy'),
('hQyM4YDXQ_qIC2kdFfzVEQ==', null, 'Teppo',     'Ilovuori', 'teppo@testi.fi',               '346674574',    'Helsinki',     'Finland', 'I do not care'),
('Y13LEFxMTbiHwlgGgUlTrQ==', null, 'Liisa',     'Joki',     'liisa@joki.fi',                '475746776',    'Turku',        'Finland', 'Ice cream is good'),
('WvaGqpLbRX+UXeLc8KDkNg==', null, 'Sami',      'Linna',    'sami@linna.fi',                '457746767',    'Helsinki',     'Finland', 'Puppies!'),
('O5Uh+GHVQ46OtjTAHbwIsA==', null, 'Henrik',    'Puro',     'hpuro@puro.org',               '467674767467', 'Espoo',        'Finland', 'Money money'),
('TUaFLKarSqK8YxEwao8w1w==', null, 'Olaf',      'Vaara',    'olle@vaara',                   '467674685',    'Espoo',        'Finland', 'What ever'),
('jenKI+UVQXWoweeSobbcxQ==', null, 'Mikko',     'Talo',     'mikkot@gmail.com',             '23425754',     'Espoo',        'Finland', 'something something'),
('JSokAKC2SO6o91b6uAGlkA==', null, 'Elvis',     'Lehti',    'lehti@test.com',               '123423536',    'Pori',         'Finland', 'Likes pandas'),
('l0kZ7iCfTXeChpqQ_6iTqA==', null, 'Oskari',    'Vuononen', 'oskari.vuononen@hotmale.com',  '14653474',     'Kotka',        'Finland', 'Eats sausages'),
('pg4W68RvT3K_R5GvYUU38Q==', null, 'Johannes',  'Mäki',     'johannes.maki@maki.org',       '1234123423',   'Tampere',      'Finland', 'Trains'),
('biAWzE1KQ0e+Ty7vigO+KQ==', null, 'Joona',     'Virtanen', 'jonna@gmail.com',              '45774574',     'Tampere',      'Finland', 'Once ate a blueberry'),
('WN8_u2lKQ4Gfic8axp8q2g==', null, 'Lauri',     'Pietilä',  'lauri@lauri.fi',               '8768455647',   'Tampere',      'Finland', 'Has a very big p----'),
('xZ3I2jNKRTiQeLIMIhlkAA==', null, 'Sampo',     'Testaaja', 'sampo@testi.fi',               '12335264',     'Stockholm',    'Sweden', 'Pappa betalar'),
('EV6yiCnuSp+Ljsh5WJl6jg==', null, 'Ville',     'Seppä',    'ville@ville.fi',               '123453235',    'Vantaa',       'Finland', 'Oispa kaljaa'),
('HABVgZl+RMqLnC9WeL5+Sg==', null, 'Sampsa',    'Laitila',  'sampsa@abc.com',               '764577475',    'Oulu',         'Finland', 'Why?'),
('BfpOto0YSnmRPjRLnU4ijw==', null, 'Laura',     'Kyyrö',    'lk@gmail.com',                 '1234214342',   'Oulu',         'Finland', 'Lets go'),
('f8UWKgX2RuqRuy_tSZGe0A==', null, 'Heidi',     'Haitila',  'heidi@hotmail.com',            '3423252531',   'Vaasa',        'Finland', 'maybe but no'),
('SNIcyofxTl+Oqza4ZZvMgw==', null, 'Aliisa',    'Alatila',  'aliisa@hotmail.com',           '1242365567',   'Lappeenranta', 'Finland', 'last two'),
('5s7s9+IMTfi4ahPtZjB9SA==', null, 'Maija',     'Huippu',   'maija@gmail.com',              '12335546',     'Salo',         'Finland', 'bye bye');